# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: ~/zsh
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /home/vagrant/zsh
    type: nfs

#Todo: Execute setup after provision
#post_provision_scripts:
#  - ~/zsh/platforms/linux/setup.sh
